In [2]:
import numpy as np

## 矩陣

In [3]:
m1=np.mat('1 2;3 4')
m2=np.mat('1 0;0 1') #identity matrix，任何矩陣乘以其後維持原樣
m3=m1*m2 #也可以寫成np.dot(m1,m2)
m4=m1*m1 #也可以寫成m1**2
m5=np.linalg.inv(m1) #反矩陣
m6=np.matrix.transpose(m1) #行列互換
a1=np.asarray(m1) #矩陣轉陣列
print(m1,'\n')
print(m2,'\n')
print(m3,'\n')
print(m4,'\n')
print(m5,'\n')
print(m6,'\n')

[[1 2]
 [3 4]] 

[[1 0]
 [0 1]] 

[[1 2]
 [3 4]] 

[[ 7 10]
 [15 22]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 

[[1 3]
 [2 4]] 



## 陣列

In [4]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[1,0],[0,1]])
a3=a1*a2 #如果寫成np.dot(a1,a2)，會以矩陣方法相乘
a4=a1*a1 #也可以寫成a1**2
m1=np.asmatrix(a1) #陣列轉矩陣
print(a1,'\n')
print(a2,'\n')
print(a3,'\n')
print(a4,'\n')

[[1 2]
 [3 4]] 

[[1 0]
 [0 1]] 

[[1 0]
 [0 4]] 

[[ 1  4]
 [ 9 16]] 

